### upload spreadsheet for specific entity
PUT http://localhost:4004/odata/v4/importer/Spreadsheet(entity='my.bookshop.Books')/content
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< .\spreadsheettest.xlsx

### get spreadsheet template for entity
GET http://localhost:4004/odata/v4/importer/Spreadsheet(entity="Books")/content

### check if import was successful
GET http://localhost:4004/odata/v4/catalog/Books